name: "Build e teste"

on:
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Clonando o projeto"
      uses: actions/checkout@v4

    
    - name: "Incluindo o JDK 21"
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: "Buildando o projeto"
      run: mvn -B install -f pom.xml
    - name: Rodar SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=Zodh_zodh-video-service \
          -Dsonar.organization=zodh-hackaton \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.branch.name=${{ github.ref_name }}

    - name: Aguardar análise do SonarQube
      run: sleep 30

    - name: Verificar Quality Gate SonarQube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
          "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Zodh_zodh-video-service" \
          | jq -r .projectStatus.status)

        if [[ "$STATUS" == "ERROR" ]]; then
          echo "❌ Quality Gate falhou! O build será interrompido."
          exit 1
        else
          echo "✅ Quality Gate aprovado! Build continua."
        fi